<?php
/**
 * Generates database/migrations/002_reference_data.sql from the scoring sources:
 *   docs/scoring/ipip16_items.tsv   (163 IPIP items + keying)
 *   docs/scoring/norms.json         (factor/domain norms, percentile tables)
 *   database/tools/factors_content.json (factor & domain copy shown in the UI)
 *
 * Usage:  php database/tools/build-seeds.php
 * The generated SQL is committed; re-run only when the sources change.
 */
declare(strict_types=1);

const ITEM_SET_VERSION = 'ipip16-v1';
const FACTOR_ORDER = ['A', 'B', 'C', 'E', 'F', 'G', 'H', 'I', 'L', 'M', 'N', 'O', 'Q1', 'Q2', 'Q3', 'Q4'];
const DOMAIN_WEIGHTS = [
    'EX' => ['A' => 1, 'F' => 1, 'H' => 1, 'N' => -1, 'Q2' => -1],
    'AX' => ['C' => -1, 'L' => 1, 'O' => 1, 'Q4' => 1],
    'TM' => ['A' => -1, 'I' => -1, 'M' => -1, 'Q1' => -1],
    'IN' => ['E' => 1, 'H' => 1, 'L' => 1, 'Q1' => 1],
    'SC' => ['F' => -1, 'G' => 1, 'M' => -1, 'Q3' => 1],
];
// Attention checks: [code, 1-based final position, expected answer, text]
const ATTENTION_CHECKS = [
    ['ATT1', 35, 4, "To show you are reading carefully, please select 'Agree' for this statement."],
    ['ATT2', 85, 2, "Please select 'Disagree' for this statement to confirm your attention."],
    ['ATT3', 135, 5, "To confirm you are paying attention, please select 'Strongly Agree' here."],
];

$root = dirname(__DIR__, 2);

function q(string|int|float|null $v): string
{
    if ($v === null) {
        return 'NULL';
    }
    if (is_int($v) || is_float($v)) {
        return (string) $v;
    }
    return "'" . str_replace(["\\", "'"], ["\\\\", "''"], $v) . "'";
}

function fail(string $msg): never
{
    fwrite(STDERR, "ERROR: $msg\n");
    exit(1);
}

// ---------------------------------------------------------------- load sources
$content = json_decode(file_get_contents("$root/database/tools/factors_content.json"), true, flags: JSON_THROW_ON_ERROR);
$norms = json_decode(file_get_contents("$root/docs/scoring/norms.json"), true, flags: JSON_THROW_ON_ERROR);

$itemsByFactor = [];
$lines = file("$root/docs/scoring/ipip16_items.tsv", FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
array_shift($lines); // header
foreach ($lines as $line) {
    [$code, $factor, $keyed, $text] = explode("\t", $line, 4);
    $itemsByFactor[$factor][] = ['code' => $code, 'factor' => $factor, 'keyed' => $keyed, 'text' => $text];
}
if (array_sum(array_map('count', $itemsByFactor)) !== 163) {
    fail('expected 163 IPIP items');
}

// ------------------------------------------------- per-factor alternating order
// Interleave positively and negatively keyed items (+,-,+,-,...) to limit
// acquiescence runs, then append whatever remains of the larger group.
$sequences = [];
foreach (FACTOR_ORDER as $f) {
    $pos = array_values(array_filter($itemsByFactor[$f], fn ($i) => $i['keyed'] === '+'));
    $neg = array_values(array_filter($itemsByFactor[$f], fn ($i) => $i['keyed'] === '-'));
    $seq = [];
    for ($i = 0; $i < max(count($pos), count($neg)); $i++) {
        if (isset($pos[$i])) {
            $seq[] = $pos[$i];
        }
        if (isset($neg[$i])) {
            $seq[] = $neg[$i];
        }
    }
    $sequences[$f] = $seq;
}

// ----------------------------------- round-robin across factors (10 rounds)
// Factor B has 13 items; its 3 extra items are slotted in after rounds 3, 6, 9.
$ordered = [];
$bExtra = array_slice($sequences['B'], 10);
for ($round = 0; $round < 10; $round++) {
    foreach (FACTOR_ORDER as $f) {
        $ordered[] = $sequences[$f][$round];
    }
    if (in_array($round, [2, 5, 8], true)) {
        $ordered[] = array_shift($bExtra);
    }
}

foreach (ATTENTION_CHECKS as [$code, $position, $expected, $text]) {
    array_splice($ordered, $position - 1, 0, [[
        'code' => $code, 'factor' => null, 'keyed' => null, 'text' => $text, 'expected' => $expected,
    ]]);
}

// ------------------------------------------------------------------ sanity checks
if (count($ordered) !== 166) {
    fail('expected 166 items after inserting attention checks, got ' . count($ordered));
}
$codes = array_column($ordered, 'code');
if (count(array_unique($codes)) !== 166) {
    fail('duplicate item codes');
}
for ($i = 1; $i < count($ordered); $i++) {
    $a = $ordered[$i - 1]['factor'];
    $b = $ordered[$i]['factor'];
    if ($a !== null && $a === $b) {
        fail("adjacent items share factor $a at position " . ($i + 1));
    }
}
foreach (ATTENTION_CHECKS as [$code, $position]) {
    if ($ordered[$position - 1]['code'] !== $code) {
        fail("$code not at position $position");
    }
}

// ------------------------------------------------------------------- emit SQL
$out = [];
$out[] = '-- =============================================================================';
$out[] = '-- GENERATED by database/tools/build-seeds.php — do not edit by hand.';
$out[] = '-- Item set ' . ITEM_SET_VERSION . ' (163 IPIP items + 3 attention checks)';
$out[] = "-- Norm set {$norms['version']} (N = {$norms['n']}, {$norms['source']})";
$out[] = '-- =============================================================================';
$out[] = '';

$rows = [];
foreach ($content['factors'] as $f) {
    $rows[] = '(' . implode(', ', [
        q($f['code']), q($f['name']), q($f['lowLabel']), q($f['highLabel']), q($f['category']),
        q($f['shortDesc']), q($f['detailedDesc']), q($f['lowPoleDesc']), q($f['averagePoleDesc']),
        q($f['highPoleDesc']), q($f['workplaceImpact']), q((int) $f['sortOrder']),
    ]) . ')';
}
$out[] = 'INSERT INTO factors (code, name, low_label, high_label, category, short_desc, detailed_desc, low_desc, average_desc, high_desc, workplace_impact, sort_order) VALUES';
$out[] = implode(",\n", $rows) . ';';
$out[] = '';

$rows = [];
foreach ($content['domains'] as $d) {
    $rows[] = '(' . implode(', ', [q($d['code']), q($d['name']), q($d['description']), q((int) $d['sortOrder'])]) . ')';
}
$out[] = 'INSERT INTO domains (code, name, description, sort_order) VALUES';
$out[] = implode(",\n", $rows) . ';';
$out[] = '';

$rows = [];
foreach (DOMAIN_WEIGHTS as $domain => $weights) {
    if ($weights !== $norms['globals'][$domain]['weights']) {
        fail("domain weights for $domain differ from norms.json");
    }
    foreach ($weights as $factor => $w) {
        $rows[] = '(' . implode(', ', [q($domain), q($factor), q($w)]) . ')';
    }
}
$out[] = 'INSERT INTO domain_weights (domain_code, factor_code, weight) VALUES';
$out[] = implode(",\n", $rows) . ';';
$out[] = '';

$out[] = 'INSERT INTO item_sets (version, description, is_active) VALUES';
$out[] = '(' . q(ITEM_SET_VERSION) . ", 'IPIP 16PF scales (163 items, public domain) + 3 attention checks', 1);";
$out[] = '';

$rows = [];
foreach ($ordered as $idx => $item) {
    $rows[] = '(' . implode(', ', [
        q(ITEM_SET_VERSION), q($item['code']), q($item['factor']), q($item['keyed']),
        $item['factor'] === null ? '1' : '0', q($item['expected'] ?? null), q($item['text']), q($idx + 1),
    ]) . ')';
}
$out[] = 'INSERT INTO items (item_set_version, item_code, factor_code, keyed, is_attention_check, expected_answer, text, position) VALUES';
$out[] = implode(",\n", $rows) . ';';
$out[] = '';

$out[] = 'INSERT INTO norm_sets (version, source, sample_size, is_active) VALUES';
$out[] = '(' . implode(', ', [
    q($norms['version']),
    q('Open Psychometrics 16PF open dataset (openpsychometrics.org/_rawdata), complete responses aged 13-100'),
    q((int) $norms['n']),
]) . ', 1);';
$out[] = '';

$normRows = [];
$pctRows = [];
foreach (FACTOR_ORDER as $f) {
    $n = $norms['factors'][$f] ?? fail("norms missing factor $f");
    $normRows[] = '(' . implode(', ', [q($norms['version']), q($f), q($n['mean']), q($n['sd']), q((int) $norms['n']), q($n['alpha'])]) . ')';
    foreach ($n['percentiles'] as $raw => $pct) {
        $pctRows[] = '(' . implode(', ', [q($norms['version']), q($f), q((int) $raw), q((float) $pct)]) . ')';
    }
}
$out[] = 'INSERT INTO factor_norms (norm_version, factor_code, mean, sd, n, alpha) VALUES';
$out[] = implode(",\n", $normRows) . ';';
$out[] = '';
$out[] = 'INSERT INTO factor_percentiles (norm_version, factor_code, raw_score, percentile) VALUES';
$out[] = implode(",\n", $pctRows) . ';';
$out[] = '';

$rows = [];
foreach (DOMAIN_WEIGHTS as $domain => $_) {
    $g = $norms['globals'][$domain];
    $rows[] = '(' . implode(', ', [q($norms['version']), q($domain), q($g['mean']), q($g['sd'])]) . ')';
}
$out[] = 'INSERT INTO domain_norms (norm_version, domain_code, mean, sd) VALUES';
$out[] = implode(",\n", $rows) . ';';
$out[] = '';

$target = "$root/database/migrations/002_reference_data.sql";
file_put_contents($target, implode("\n", $out));
printf("Wrote %s (%d items, %d percentile rows)\n", $target, count($ordered), count($pctRows));
